import { ArrowRight, CheckCircle2 } from "lucide-react";
import { SiteFooter, SiteHeader } from "../site-chrome";

const measures = [["Bust", "Around the fullest part, keeping the tape comfortably level."], ["Waist", "Around your natural waist—do not pull the tape too tightly."], ["Shoulder", "From one shoulder edge to the other across the back."], ["Frock length", "From the highest shoulder point to your preferred finished length."], ["Sleeve", "From shoulder edge to wrist, with the arm slightly relaxed."], ["Armhole", "Around the shoulder joint with enough room to move comfortably."]];

export default function FitRoom() {
  return <main className="min-h-screen bg-[#fcfaf7] text-[#2a1722]"><SiteHeader /><section className="mx-auto grid max-w-[1440px] lg:grid-cols-[1.05fr_.95fr]"><div className="flex min-h-[560px] flex-col justify-center px-7 py-16 sm:px-14 lg:px-20"><p className="text-xs uppercase tracking-[.22em] text-[#8b3e67]">The Fit Room</p><h1 className="mt-5 font-serif text-[clamp(3.6rem,7vw,7rem)] leading-[.9]">Measure once.<br /><em className="font-light text-[#8b3e67]">Feel good all day.</em></h1><p className="mt-7 max-w-xl leading-7 text-[#6d5963]">A better fit begins with six simple measurements. Wear light clothing, stand naturally and ask someone to help where possible.</p></div><div className="min-h-[540px] bg-[#3f1731] p-8 sm:p-14"><div className="flex h-full flex-col justify-between border border-white/15 p-7 text-white sm:p-10"><p className="text-xs uppercase tracking-[.2em] text-white/45">Before you begin</p><div className="space-y-5">{["Use a soft measuring tape", "Keep the tape level—not tight", "Record in inches", "Measure twice before sending"].map((tip) => <p key={tip} className="flex items-center gap-3 font-serif text-xl sm:text-2xl"><CheckCircle2 className="text-[#d6a5bc]" size={20} />{tip}</p>)}</div><p className="text-sm leading-6 text-white/55">No measuring tape? Send us the measurements of a similar garment that fits you well.</p></div></div></section>
    <section className="mx-auto max-w-[1100px] px-6 py-20 lg:py-28"><div className="text-center"><p className="text-xs uppercase tracking-[.2em] text-[#8b3e67]">Your six-point fit</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">A simple measurement guide</h2></div><div className="mt-12 grid gap-px overflow-hidden border border-[#3f1731]/10 bg-[#3f1731]/10 sm:grid-cols-2 lg:grid-cols-3">{measures.map(([name, text], index) => <div key={name} className="bg-white p-7"><span className="text-xs text-[#a17a8e]">0{index + 1}</span><h3 className="mt-4 font-serif text-2xl">{name}</h3><p className="mt-3 text-sm leading-6 text-[#705c66]">{text}</p></div>)}</div><div className="mt-12 flex flex-col items-center bg-[#f1e5e9] p-10 text-center"><h3 className="font-serif text-3xl">Still unsure about your fit?</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#705c66]">Choose “Not sure” in the design room and we’ll guide you through the measurements personally.</p><a href="/design-your-own" className="mt-6 flex items-center gap-2 border-b border-[#3f1731] pb-1 text-sm">Visit the co-create room <ArrowRight size={15} /></a></div></section><SiteFooter /></main>;
}
