"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CreditCard, Minus, Plus, Search, ShieldCheck, ShoppingBasket, Smartphone, Truck } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { SiteFooter, SiteHeader } from "./site-chrome";

type Product = { id: number; name: string; category: string; price: number; badge?: string; image: string; description: string };
type CartItem = { product: Product; quantity: number; size: string };
type CheckoutStep = "delivery" | "payment" | "review" | "complete";

const products: Product[] = [
  { id: 1, name: "Mahnoor Berry Frock", category: "Printed cotton", price: 6490, badge: "Most loved", image: "/eloria-hero-v2.png", description: "A softly gathered berry frock with a full skirt, easy sleeves and room to move." },
  { id: 2, name: "Gul Cream Frock", category: "Everyday florals", price: 7290, badge: "New", image: "/eloria-floral-v2.png", description: "Lightweight cream cotton scattered with tiny flowers and finished with a tiered hem." },
  { id: 3, name: "Rani Raspberry Frock", category: "Evening ease", price: 7950, image: "/eloria-raspberry-v2.png", description: "A deep raspberry floral with delicate piping and a relaxed, generous skirt." },
  { id: 4, name: "Mahnoor Custom Frock", category: "Made to order", price: 8490, image: "/eloria-hero-v2.png", description: "Our signature berry silhouette, available in custom length and colour." },
];

const categories = [
  { name: "Everyday", note: "Cotton frocks for regular plans", image: "/eloria-floral-v2.png" },
  { name: "Evening", note: "Deeper colour, an easy silhouette", image: "/eloria-raspberry-v2.png" },
  { name: "Florals", note: "Small prints and soft movement", image: "/eloria-floral-v2.png" },
  { name: "Made for You", note: "Your length, colour and fit", image: "/eloria-hero-v2.png" },
];

export function Storefront() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [selected, setSelected] = useState<Product | null>(null);
  const [size, setSize] = useState("M");
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [checkoutStep, setCheckoutStep] = useState<CheckoutStep>("delivery");
  const [payment, setPayment] = useState("cod");
  const [city, setCity] = useState("Bahawalpur");
  const [customer, setCustomer] = useState({ name: "", phone: "", email: "", address: "", notes: "" });
  const [orderNumber, setOrderNumber] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const matches = products.filter((product) => `${product.name} ${product.category} ${product.description}`.toLowerCase().includes(query.trim().toLowerCase()));

  useEffect(() => { const saved = window.localStorage.getItem("eloria-cart"); if (saved) try { setCart(JSON.parse(saved)); } catch {} }, []);
  useEffect(() => { window.localStorage.setItem("eloria-cart", JSON.stringify(cart)); }, [cart]);

  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0), [cart]);
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const shipping = subtotal >= 10000 ? 0 : 250;
  const total = subtotal + shipping;

  const addToCart = (product: Product, chosenSize = size) => {
    setCart((current) => { const found = current.findIndex((item) => item.product.id === product.id && item.size === chosenSize); return found < 0 ? [...current, { product, quantity: 1, size: chosenSize }] : current.map((item, index) => index === found ? { ...item, quantity: item.quantity + 1 } : item); });
    setSelected(null);
  };

  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool?: (tool: unknown, options?: unknown) => void } }).modelContext;
    if (!modelContext?.registerTool) return;
    const lifecycle = new AbortController();
    modelContext.registerTool({ name: "add_product_to_cart", title: "Add product to cart", description: "Add an ELORIA piece to the shopping bag.", inputSchema: { type: "object", properties: { productId: { type: "number" }, size: { type: "string", enum: ["XS", "S", "M", "L", "XL"] } }, required: ["productId", "size"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: unknown) => { const value = input as { productId: number; size: string }; const product = products.find((item) => item.id === value.productId); if (!product) throw new Error("Product not found"); addToCart(product, value.size); return { product: product.name, size: value.size, status: "added" }; } }, { signal: lifecycle.signal });
    return () => lifecycle.abort();
  }, []);

  const updateQuantity = (index: number, change: number) => setCart((current) => current.flatMap((item, itemIndex) => itemIndex !== index ? [item] : item.quantity + change > 0 ? [{ ...item, quantity: item.quantity + change }] : []));
  const submitDelivery = (event: FormEvent) => { event.preventDefault(); setCheckoutStep("payment"); };
  const placeOrder = () => { setOrderNumber(`EL-${Date.now().toString().slice(-6)}`); setCheckoutStep("complete"); setCart([]); };
  const orderMessage = encodeURIComponent(`Assalam-o-Alaikum ELORIA, I have placed order ${orderNumber}. Please confirm it for me.`);

  return <main className="min-h-screen overflow-x-hidden bg-[#fffdfb] text-[#2b1722]">
    <SiteHeader actions={<><button onClick={() => setSearchOpen(true)} aria-label="Search products"><Search size={20} strokeWidth={1.7} /></button><Sheet><SheetTrigger asChild><button className="relative" aria-label={`Shopping bag with ${count} items`}><ShoppingBasket size={20} />{count > 0 && <span className="absolute -right-2.5 -top-2.5 grid h-5 min-w-5 place-items-center rounded-full bg-[#8b3e67] px-1 text-[0.65rem] text-white">{count}</span>}</button></SheetTrigger><SheetContent className="flex w-full flex-col bg-[#fffdfb] p-0 sm:max-w-md"><SheetHeader className="border-b border-[#3f1731]/10 p-6"><SheetTitle className="font-serif text-2xl">Shopping bag</SheetTitle><SheetDescription>{count ? `${count} item${count > 1 ? "s" : ""}` : "Your bag is empty."}</SheetDescription></SheetHeader><div className="flex-1 space-y-5 overflow-y-auto p-6">{cart.map((item, index) => <div key={`${item.product.id}-${item.size}`} className="grid grid-cols-[82px_1fr] gap-4"><img src={item.product.image} alt="" className="aspect-[3/4] h-full w-full object-cover" /><div><p className="font-serif text-lg">{item.product.name}</p><p className="mt-1 text-xs uppercase tracking-[.12em] text-[#765f6b]">Size {item.size}</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center gap-3 border border-[#3f1731]/15 px-2 py-1"><button onClick={() => updateQuantity(index, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><span className="w-4 text-center text-sm">{item.quantity}</span><button onClick={() => updateQuantity(index, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div><span className="text-sm font-medium">Rs. {(item.product.price * item.quantity).toLocaleString("en-PK")}</span></div></div></div>)}{!cart.length && <div className="grid min-h-64 place-items-center text-center text-[#78636e]"><div><ShoppingBasket className="mx-auto mb-4 opacity-35" size={34} /><p>Add a piece you love and it will appear here.</p></div></div>}</div><div className="border-t border-[#3f1731]/10 p-6"><div className="mb-5 flex justify-between"><span>Subtotal</span><strong>Rs. {subtotal.toLocaleString("en-PK")}</strong></div><Button disabled={!cart.length} onClick={() => { setCheckoutStep("delivery"); setCheckoutOpen(true); }} className="h-12 w-full rounded-none bg-[#3f1731] text-white">Checkout</Button><p className="mt-3 text-center text-xs text-[#7c6973]">Free delivery on orders over Rs. 10,000</p></div></SheetContent></Sheet></>} />

    <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffdfb] sm:max-w-xl"><DialogHeader><DialogTitle className="font-serif text-2xl">Search ELORIA</DialogTitle><DialogDescription>Find a frock by name, colour or style.</DialogDescription></DialogHeader><label className="flex items-center gap-3 border border-[#3f1731]/20 bg-white px-4"><Search size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try berry, floral or custom" className="h-12 w-full outline-none" aria-label="Search products" /></label><div className="grid gap-3">{matches.length ? matches.map((product) => <button key={product.id} onClick={() => { setSearchOpen(false); setSelected(product); setSize("M"); }} className="flex items-center gap-4 border-b border-[#3f1731]/10 py-3 text-left"><img src={product.image} alt="" className="h-20 w-16 object-cover" /><span><strong className="block font-serif text-lg">{product.name}</strong><span className="text-sm text-[#705b66]">{product.category} · Rs. {product.price.toLocaleString("en-PK")}</span></span></button>) : <p className="py-8 text-center text-[#705b66]">No pieces found. Try another name or colour.</p>}</div></DialogContent></Dialog>
    <section className="relative mx-auto min-h-[calc(100svh-106px)] max-w-[1440px] overflow-hidden bg-[#eadde2] lg:grid lg:min-h-[720px] lg:grid-cols-[.86fr_1.14fr]"><img src="/eloria-hero-v2.png" alt="Woman wearing ELORIA berry floral frock" className="absolute inset-0 h-full w-full object-cover object-[52%_center] lg:hidden" /><div className="absolute inset-0 bg-gradient-to-t from-[#2a0d21] via-[#3f1731]/40 to-transparent lg:hidden" /><div className="relative z-10 flex min-h-[calc(100svh-106px)] flex-col justify-end px-6 pb-12 text-white sm:px-10 lg:min-h-[720px] lg:justify-center lg:px-16 lg:text-[#2b1722]"><p className="mb-5 text-sm tracking-[.16em] text-white/75 lg:text-[#8b3e67]">NEW PRINTED FROCKS</p><h1 className="max-w-xl font-serif text-[clamp(3.7rem,15vw,6rem)] leading-[.88] tracking-[-.04em] lg:text-[clamp(4rem,7vw,7rem)]">The dress you’ll<br /><em className="font-light text-[#f2b9d3] lg:text-[#8b3e67]">reach for again.</em></h1><p className="mt-6 max-w-md text-base leading-7 text-white/80 lg:text-[#684f5b]">Soft printed frocks for lunches, evenings out and all the ordinary days in between.</p><div className="mt-8 flex gap-3"><a href="/collections/frocks" className="inline-flex h-12 items-center bg-white px-6 font-medium text-[#3f1731] lg:bg-[#3f1731] lg:text-white">Shop frocks</a><a href="/design-your-own" className="inline-flex h-12 items-center border border-white/50 px-5 font-medium lg:border-[#3f1731]/30">Custom order</a></div></div><div className="hidden min-h-[720px] lg:block"><img src="/eloria-hero-v2.png" alt="Woman wearing a berry floral frock" className="h-full w-full object-cover object-center" /></div></section>

    <section className="bg-[#3f1731] px-5 py-4 text-white"><div className="mx-auto flex max-w-[1100px] flex-wrap justify-center gap-x-10 gap-y-2 text-sm"><span>Made in Pakistan</span><span>Sizes XS–XL</span><span>Custom length available</span><span>Cash on delivery</span></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-10 lg:py-28"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-[#8b3e67]">SHOP BY MOOD</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">What are you dressing for?</h2></div><p className="max-w-md leading-7 text-[#705b66]">Start with the day you have in mind. We’ll help with sizing or small changes before you order.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <a key={category.name} href={`/collections/frocks?category=${encodeURIComponent(category.name)}`} className={`group relative min-h-[430px] overflow-hidden ${index % 2 ? "lg:mt-10" : ""}`}><img src={category.image} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#260b1d]/90 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white"><h3 className="font-serif text-3xl">{category.name}</h3><p className="mt-2 text-sm text-white/70">{category.note}</p><span className="mt-5 inline-flex items-center gap-2 text-sm">See the edit <ArrowRight size={15} /></span></div></a>)}</div></section>

    <section className="border-y border-[#3f1731]/10 bg-[#f7eef1] px-5 py-20 sm:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="mb-10 flex items-end justify-between"><div><p className="text-sm text-[#8b3e67]">JUST IN</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Fresh from the rack</h2></div><a href="/collections/frocks" className="hidden items-center gap-2 border-b border-[#3f1731] pb-1 sm:flex">View all <ArrowRight size={15} /></a></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 lg:grid-cols-4 lg:gap-5">{products.map((product) => <article key={product.id} className="group cursor-pointer" onClick={() => { setSelected(product); setSize("M"); }}><div className="relative overflow-hidden bg-white"><img src={product.image} alt={product.name} className="aspect-[3/4] h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]" />{product.badge && <span className="absolute left-3 top-3 bg-white/95 px-3 py-1 text-xs">{product.badge}</span>}<button onClick={(event) => { event.stopPropagation(); addToCart(product); }} className="absolute inset-x-3 bottom-3 translate-y-16 bg-white/95 py-3 font-medium shadow-lg transition group-hover:translate-y-0 focus:translate-y-0">Quick add — M</button></div><p className="mt-4 text-xs uppercase tracking-[.12em] text-[#856d7a]">{product.category}</p><div className="mt-1 sm:flex sm:justify-between sm:gap-2"><h3 className="font-serif text-lg">{product.name}</h3><p className="mt-1 shrink-0 text-sm sm:mt-0">Rs. {product.price.toLocaleString("en-PK")}</p></div></article>)}</div></div></section>

    <section className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><img src="/eloria-floral-v2.png" alt="Cream floral ELORIA frock" className="h-[420px] w-full object-cover lg:h-[600px]" /><div className="flex flex-col justify-center bg-[#3f1731] px-8 py-12 text-white sm:px-16 lg:px-20"><p className="text-sm text-[#d9a5be]">NEED A SMALL CHANGE?</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight sm:text-6xl">Keep the dress.<br />Change what matters.</h2><p className="mt-6 max-w-lg leading-7 text-white/65">Ask for a different length, sleeve or colour. Send your measurements and we’ll confirm what’s possible before you pay.</p><a href="/design-your-own" className="mt-9 inline-flex w-fit items-center gap-3 bg-white px-6 py-3 font-medium text-[#3f1731]">Start a custom order <ArrowRight size={16} /></a></div></section>

    <section className="mx-auto grid max-w-[1200px] gap-8 px-6 py-20 text-center sm:grid-cols-3 lg:py-24"><Info icon={Truck} title="Delivery across Pakistan">Orders usually arrive in 3–5 working days. Made-to-order pieces take longer.</Info><Info icon={CreditCard} title="Pay your way">Cash on delivery, bank transfer, Easypaisa, JazzCash and cards.</Info><Info icon={ShieldCheck} title="Help before checkout">Unsure about size or fabric? Message us before placing the order.</Info></section>
    <SiteFooter />

    <Dialog open={!!selected} onOpenChange={(open) => !open && setSelected(null)}>{selected && <DialogContent className="max-h-[92vh] overflow-y-auto border-none bg-[#fffdfb] p-0 sm:max-w-4xl"><div className="grid md:grid-cols-2"><img src={selected.image} alt={selected.name} className="h-full min-h-[460px] w-full object-cover" /><div className="flex flex-col justify-center p-7 sm:p-10"><DialogHeader><p className="text-sm text-[#8b3e67]">{selected.category}</p><DialogTitle className="font-serif text-4xl font-normal">{selected.name}</DialogTitle><DialogDescription className="text-base leading-7 text-[#6d5863]">{selected.description}</DialogDescription></DialogHeader><p className="mt-6 text-lg font-medium">Rs. {selected.price.toLocaleString("en-PK")}</p><div className="mt-8"><p className="mb-3 font-medium">Choose a size</p><div className="flex flex-wrap gap-2">{["XS", "S", "M", "L", "XL"].map((option) => <button key={option} onClick={() => setSize(option)} className={`grid h-11 w-12 place-items-center border ${size === option ? "border-[#3f1731] bg-[#3f1731] text-white" : "border-[#3f1731]/20"}`}>{option}</button>)}</div></div><Button onClick={() => addToCart(selected)} className="mt-8 h-12 rounded-none bg-[#3f1731] text-white">Add to bag</Button><a href="/fit-room" className="mt-4 text-sm underline underline-offset-4">Check the measurement guide</a></div></div></DialogContent>}</Dialog>

    <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="max-h-[94vh] overflow-y-auto bg-[#fffdfb] p-0 sm:max-w-3xl"><div className="p-6 sm:p-9"><DialogHeader><DialogTitle className="font-serif text-3xl">{checkoutStep === "complete" ? "Order received" : "Checkout"}</DialogTitle><DialogDescription>{checkoutStep === "complete" ? "We’ll confirm your order by phone or WhatsApp." : "Your delivery details are only used to complete this order."}</DialogDescription></DialogHeader>{checkoutStep !== "complete" && <div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>{checkoutStep === "delivery" ? "Delivery" : checkoutStep === "payment" ? "Payment" : "Review"}</span><span>{checkoutStep === "delivery" ? "1" : checkoutStep === "payment" ? "2" : "3"} of 3</span></div><Progress value={checkoutStep === "delivery" ? 33 : checkoutStep === "payment" ? 66 : 100} className="h-1.5" /></div>}
      {checkoutStep === "delivery" && <form onSubmit={submitDelivery} className="mt-7 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={customer.name} onChange={(value) => setCustomer({ ...customer, name: value })} /><Field label="Mobile number" type="tel" value={customer.phone} onChange={(value) => setCustomer({ ...customer, phone: value })} /></div><Field label="Email (optional)" type="email" required={false} value={customer.email} onChange={(value) => setCustomer({ ...customer, email: value })} /><label className="grid gap-2 font-medium">City<select value={city} onChange={(event) => setCity(event.target.value)} className="h-12 border border-[#3f1731]/15 bg-white px-3 font-normal outline-none"><option>Bahawalpur</option><option>Lahore</option><option>Karachi</option><option>Islamabad / Rawalpindi</option><option>Multan</option><option>Faisalabad</option><option>Other city</option></select></label><label className="grid gap-2 font-medium">Complete delivery address<textarea required value={customer.address} onChange={(event) => setCustomer({ ...customer, address: event.target.value })} className="min-h-24 border border-[#3f1731]/15 bg-white p-3 font-normal outline-none" placeholder="House, street, area and a nearby landmark" /></label><Button className="mt-2 h-12 rounded-none bg-[#3f1731] text-white">Continue to payment <ArrowRight /></Button></form>}
      {checkoutStep === "payment" && <div className="mt-7"><RadioGroup value={payment} onValueChange={setPayment} className="gap-3">{[["cod", "Cash on delivery", "Pay in cash when your parcel arrives", Truck], ["wallet", "Easypaisa or JazzCash", "Transfer details are shared after confirmation", Smartphone], ["bank", "Bank transfer", "Account details are shared after confirmation", CreditCard], ["card", "Debit or credit card", "Available when secure card processing is connected", CreditCard]].map(([value, title, note, Icon]) => { const PaymentIcon = Icon as typeof Truck; return <label key={String(value)} className={`flex cursor-pointer items-center gap-4 border p-4 ${payment === value ? "border-[#3f1731] bg-[#f8f0f3]" : "border-[#3f1731]/12"}`}><RadioGroupItem value={String(value)} /><PaymentIcon size={21} className="text-[#8b3e67]" /><span><strong className="block">{String(title)}</strong><span className="text-sm text-[#76616c]">{String(note)}</span></span></label>; })}</RadioGroup>{payment === "card" && <p className="mt-4 border-l-2 border-[#8b3e67] bg-[#f7eef1] p-4 text-sm leading-6">Card payment will become active when ELORIA’s payment gateway account is connected. Choose another method for this order.</p>}<div className="mt-7 flex gap-3"><Button variant="outline" onClick={() => setCheckoutStep("delivery")} className="h-12 rounded-none"><ArrowLeft /> Back</Button><Button disabled={payment === "card"} onClick={() => setCheckoutStep("review")} className="h-12 flex-1 rounded-none bg-[#3f1731] text-white">Review order <ArrowRight /></Button></div></div>}
      {checkoutStep === "review" && <div className="mt-7"><div className="grid gap-5 border-y border-[#3f1731]/10 py-5">{cart.map((item) => <div key={`${item.product.id}-${item.size}`} className="flex justify-between gap-5"><span>{item.product.name} · {item.size} × {item.quantity}</span><strong>Rs. {(item.product.price * item.quantity).toLocaleString("en-PK")}</strong></div>)}</div><div className="grid gap-2 py-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>Rs. {subtotal.toLocaleString("en-PK")}</span></div><div className="flex justify-between"><span>Delivery to {city}</span><span>{shipping ? `Rs. ${shipping}` : "Free"}</span></div><div className="mt-2 flex justify-between border-t border-[#3f1731]/10 pt-4 text-base"><strong>Total</strong><strong>Rs. {total.toLocaleString("en-PK")}</strong></div></div><div className="bg-[#f7eef1] p-4 text-sm leading-6"><strong>Deliver to:</strong> {customer.name}, {customer.address}, {city}<br /><strong>Payment:</strong> {{ cod: "Cash on delivery", wallet: "Easypaisa / JazzCash", bank: "Bank transfer", card: "Card" }[payment]}</div><label className="mt-5 grid gap-2 font-medium">Order note (optional)<textarea value={customer.notes} onChange={(event) => setCustomer({ ...customer, notes: event.target.value })} className="min-h-20 border border-[#3f1731]/15 p-3 font-normal" placeholder="Sizing or delivery instructions" /></label><div className="mt-7 flex gap-3"><Button variant="outline" onClick={() => setCheckoutStep("payment")} className="h-12 rounded-none"><ArrowLeft /> Back</Button><Button onClick={placeOrder} className="h-12 flex-1 rounded-none bg-[#3f1731] text-white">Place order</Button></div><p className="mt-3 text-center text-xs text-[#78636e]">By placing the order, you confirm that your delivery details are correct.</p></div>}
      {checkoutStep === "complete" && <div className="py-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#3f1731] text-white"><Check size={30} /></div><h3 className="mt-6 font-serif text-4xl">Thank you, {customer.name.split(" ")[0] || "lovely"}.</h3><p className="mx-auto mt-3 max-w-md leading-7 text-[#705b66]">Your order number is <strong>{orderNumber}</strong>. We’ll contact you to confirm availability and payment details.</p><a href={`https://wa.me/?text=${orderMessage}`} target="_blank" rel="noreferrer" className="mx-auto mt-7 inline-flex h-12 items-center bg-[#3f1731] px-6 font-medium text-white">Confirm on WhatsApp</a><button onClick={() => setCheckoutOpen(false)} className="mt-5 block w-full text-sm underline underline-offset-4">Continue shopping</button></div>}
    </div></DialogContent></Dialog>
  </main>;
}

function Field({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="grid gap-2 font-medium">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="h-12 border border-[#3f1731]/15 bg-white px-3 font-normal outline-none focus:border-[#3f1731]" /></label>; }
function Info({ icon: Icon, title, children }: { icon: typeof Truck; title: string; children: React.ReactNode }) { return <div><Icon className="mx-auto text-[#8b3e67]" /><h3 className="mt-4 font-serif text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#705b66]">{children}</p></div>; }
